import { build } from 'esbuild';
import { resolve } from 'node:path';
export async function buildDesktopHost(base) {
  const root = resolve(base, '..');
  const main = await build({ absWorkingDir: base, entryPoints: [resolve(root, 'host/electron-main.cjs')], bundle: true, write: false, metafile: true, format: 'cjs', platform: 'node', target: 'node24' });
  const host = await build({ absWorkingDir: base, entryPoints: [resolve(root, 'host/desktop-launch.cjs')], bundle: true, write: false, metafile: true, format: 'cjs', platform: 'node', target: 'node24', define: { CODEX_TRAFFIC_MAIN_SOURCE: JSON.stringify(main.outputFiles[0].text) } });
  return { code: '// Generated by codlet-plugins/frontend/build.mjs\n' + host.outputFiles[0].text,
    inputs: [...new Set([...Object.keys(main.metafile.inputs), ...Object.keys(host.metafile.inputs)].map(value => resolve(base, value)))] };
}
