import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const base=dirname(fileURLToPath(import.meta.url)),root=resolve(base,'..');
const entries=[['src/adapter/entry.js','bundled/codex-ui-adapter/dist/renderer.js'],['src/desktop/entry.js','bundled/codex-desktop-adapter/renderer.js'],['src/codlet/app.jsx','bundled/codlet/dist/renderer.js']];
const artifacts=[];
for(const [entry,destination] of entries){
  const result=await build({absWorkingDir:base,entryPoints:[entry],bundle:true,write:false,metafile:true,format:'cjs',platform:'browser',jsxFactory:'h',jsxFragment:'React.Fragment',target:'chrome130',minify:false,legalComments:'inline',define:{'process.env.NODE_ENV':'"production"'},loader:{'.css':'text','.svg':'text'}});
  const packages=new Set();
  for(const output of Object.values(result.metafile.outputs))for(const [name,value] of Object.entries(output.inputs)){
    const match=/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//.exec(name.replaceAll('\\','/'));
    if(match&&value.bytesInOutput)packages.add(resolve(base,match[1]));
  }
  const notices=[];
  for(const directory of [...packages].sort()){
    const pkg=JSON.parse(await readFile(resolve(directory,'package.json'),'utf8'));
    let license;
    for(const name of ['LICENSE','LICENSE.md','LICENSE.txt','license','license.md'])try{license=await readFile(resolve(directory,name),'utf8');break;}catch(error){if(error.code!=='ENOENT')throw error;}
    if(!license)throw Error(`Missing third-party notice: ${pkg.name}@${pkg.version}`);
    notices.push(`${pkg.name}@${pkg.version} (${pkg.license})\n\n${license.trim()}`);
  }
  artifacts.push([resolve(root,destination),'// Generated by codlet-plugins/frontend/build.mjs\n'+result.outputFiles[0].text+'\n/*\n'+notices.join('\n\n---\n\n').replaceAll('*/','* /')+'\n*/\n']);
}
for(const [file,contents]of artifacts){await mkdir(dirname(file),{recursive:true});await writeFile(file,contents);}
console.log('Built UI Adapter, Desktop Adapter and Codlet GUI independently of Core');
