import layout from '../../frontend/src/codlet/layout.css';
import styling from './style.css';
import {createCodletIcon} from '../../frontend/src/brand.js';
import {createCodletIcons,pluginPuzzlePath} from '../../frontend/src/icons.js';
import {createProjectLinks} from '../../frontend/src/codlet/project-links.jsx';
import {createSettingsView} from '../../frontend/src/codlet/settings.jsx';
import {Manager} from '../../frontend/src/codlet/controller.js';
import {createPreviewRuntime} from '../preview-runtime.mjs';
import {plugins,systemNames,compatibility,support,platformSummary} from './data.js';
import {isOfficialPlugin,sortPlugins,formatDownloads,formatUpdated} from '../../frontend/src/codlet/marketplace-model.js';
import {insertTag,tagAtCaret} from '../../frontend/src/codlet/tag-search.js';
let React,h,C,I,ui,Brand,ProjectLinks,Settings,settingsManager;
export const sidebarIconMarkup=`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${pluginPuzzlePath}"/></svg>`;
function SettingsPreview(){
  const owner=settingsManager,s=React.useSyncExternalStore(owner.subscribe,owner.snapshot);
  React.useEffect(()=>{let active=true;void owner.open().then(()=>{if(active)owner.settingsPage();});return()=>{active=false;owner.close();};},[owner]);
  return <Settings s={s}/>;
}
function TagHash(){return <svg className="codlet-tag-hash" width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M6.3 2.7L4.7 13.3 M11.3 2.7L9.7 13.3 M2.7 5.5H13.3 M2.7 10.5H13.3"/></svg>;}
function Tags({plugin,onSelect}){return <span className="codlet-plugin-tags">{plugin.tags.map(tag=><button key={tag} type="button" className="codlet-plugin-tag" aria-label={`筛选 #${tag}`} onClick={()=>onSelect(tag)}><TagHash/>{tag}</button>)}</span>;}
function Copy({children,error=false,role}){return <p className={'codlet-copy'+(error?' codlet-error':'')} role={role}>{children}</p>;}
function Origin({plugin}){return <span className="market-origin" aria-label={`作者：${plugin.author}`}>{plugin.author}{isOfficialPlugin(plugin)&&<C.Tooltip content="来自 Codlet 登记的官方插件仓库"><span className="market-official">官方</span></C.Tooltip>}</span>;}
function Metrics({plugin}){return <><time dateTime={plugin.publishedAt||undefined} title={plugin.publishedAt?`最新版本发布于 ${new Date(plugin.publishedAt).toLocaleDateString('zh-CN')}`:undefined}>{formatUpdated(plugin.publishedAt)}</time><span title="插件发布包的累计下载次数">{formatDownloads(plugin.downloads)}</span></>;}
function Platforms({plugin}){const result=support(plugin);return <span className={`market-platform-note${result.known?'':' market-unknown'}`}>{!result.known&&<I.InfoCircle/>}{platformSummary(plugin)}</span>;}
function SupportedSystems({plugin}){const result=support(plugin);return result.known?result.platforms.map(s=>systemNames[s]).join('、')||'不支持当前 Codlet 平台':<span className="market-unknown">作者尚未声明</span>;}
function Status({plugin,device}){const state=compatibility(plugin,device);return state==='supported'?<span className="market-compatible">适用于当前设备</span>:<span className={`market-platform-note market-${state}`}><I.InfoCircle/>{state==='unknown'?'未声明系统支持':'不适用于当前设备'}</span>;}
function App({toolbar}){
  const params=new URLSearchParams(location.search);
  const [page,setPage]=React.useState(params.get('page')||'plugins'),[from,setFrom]=React.useState('market'),[selected,setSelected]=React.useState(plugins[0]);
  const [query,setQuery]=React.useState(''),[origin,setOrigin]=React.useState('all'),[onlyDevice,setOnlyDevice]=React.useState(false),[device,setDevice]=React.useState('windows-x86_64'),[scenario,setScenario]=React.useState('normal'),[sort,setSort]=React.useState('updated');
  const [installed,setInstalled]=React.useState(Object.fromEntries(plugins.filter(p=>p.installed).map(p=>[p.id,p.installed]))),[notice,setNotice]=React.useState(false),[busy,setBusy]=React.useState(false),[trusted,setTrusted]=React.useState(false),[grants,setGrants]=React.useState([]),[enable,setEnable]=React.useState(true),[showTags,setShowTags]=React.useState(false);
  const panel=React.useRef(null),search=React.useRef(null);
  const [activeTag,setActiveTag]=React.useState(0);
  const inform=message=>document.dispatchEvent(new CustomEvent('market-preview-message',{detail:message}));
  React.useEffect(()=>{const handle=e=>{if(e.detail.device)setDevice(e.detail.device);if(e.detail.scenario){setPage('market');setScenario(e.detail.scenario);}if(e.detail.reset){setPage('plugins');setQuery('');setOrigin('all');setOnlyDevice(false);setScenario('normal');setNotice(false);}};document.addEventListener('market-preview-control',handle);return()=>document.removeEventListener('market-preview-control',handle);},[]);
  React.useEffect(()=>{panel.current?.querySelector('.codlet-scroll')?.scrollTo(0,0);},[page]);
  React.useEffect(()=>{document.dispatchEvent(new CustomEvent('market-preview-state',{detail:{scenario,device}}));},[scenario,device]);
  ui.useEscCloseStack(notice,()=>setNotice(false));
  const chooseTag=tag=>{setQuery(insertTag(query,tag,showTags?tagAtCaret(query,query.length,query.length):undefined).query);setPage('market');setScenario('normal');setShowTags(false);search.current?.focus();};
  const details=(plugin,source=page)=>{setSelected(plugin);setFrom(source);setPage('details');};
  const review=plugin=>{setSelected(plugin);setPage('review');setTrusted(false);setGrants([]);setEnable(true);};
  const goMarket=()=>{setPage('market');setScenario('normal');};
  const installedVersion=p=>installed[p.id],updatable=p=>installedVersion(p)&&installedVersion(p)!==p.version;
  const ready=trusted&&grants.length===selected.permissions.length&&compatibility(selected,device)!=='unsupported';
  const install=()=>{setNotice(false);setBusy(true);setTimeout(()=>{setInstalled(old=>({...old,[selected.id]:selected.version}));setBusy(false);setPage('details');setFrom('market');inform('演示完成：插件状态已更新，没有执行真实安装');},900);};
  const Action=({plugin})=>compatibility(plugin,device)==='unsupported'?<C.Button color="secondary" variant="soft" size="sm" disabled>不兼容</C.Button>:updatable(plugin)?<C.Button color="info" variant="soft" size="sm" onClick={()=>review(plugin)}><I.Download/>更新</C.Button>:installedVersion(plugin)?<span className="market-status">已安装</span>:<C.Button color="secondary" variant="soft" size="sm" onClick={()=>review(plugin)}><I.Plus/>安装</C.Button>;
  const Back=({onClick,label='返回'})=><C.Button color="secondary" variant="ghost" size="sm" opticallyAlign="start" onClick={onClick}><I.ArrowLeft/>{label}</C.Button>;
  const navigation=<div className="codlet-top-toolbar"><nav className="codlet-top-navigation" aria-label="Codlet 页面"><C.Button color="secondary" variant={page==='settings'?'ghost':'soft'} size="sm" onClick={()=>setPage('plugins')}>插件管理</C.Button><C.Button color="secondary" variant={page==='settings'?'soft':'ghost'} size="sm" onClick={()=>setPage('settings')}>设置</C.Button></nav>
    {['plugins','market'].includes(page)&&<div className="codlet-toolbar-actions"><C.Tooltip content={page==='market'?'刷新市场':'刷新插件'}><C.Button color="secondary" variant="ghost" size="sm" uniform aria-label={page==='market'?'刷新市场':'刷新插件'} onClick={()=>{setScenario('loading');setTimeout(()=>setScenario('normal'),650);}}><I.Regenerate/></C.Button></C.Tooltip><C.Menu><C.Menu.Trigger><C.Button color="primary" variant="solid" size="sm">添加<I.ChevronDown/></C.Button></C.Menu.Trigger><C.Menu.Content align="end" minWidth={180}><C.Menu.Item onSelect={goMarket}><I.Globe className="codlet-add-menu-icon"/>插件市场</C.Menu.Item><div className="market-menu-divider" role="separator"/><C.Menu.Item onSelect={()=>inform('此入口会新建带 Codlet 技能的对话')}><I.Cube className="codlet-add-menu-icon"/>创建插件</C.Menu.Item><C.Menu.Item onSelect={()=>setPage('import')}><I.Plus className="codlet-add-menu-icon"/>导入插件</C.Menu.Item></C.Menu.Content></C.Menu></div>}
  </div>;
  const sorts={updated:'最近更新',downloads:'最多下载',name:'名称排序'};
  const terms=query.toLowerCase().split(/\s+/).filter(Boolean),matches=sortPlugins(plugins.filter(p=>(origin==='all'||(origin==='official')===isOfficialPlugin(p))&&(!onlyDevice||compatibility(p,device)==='supported')&&terms.every(word=>word.startsWith('#')?p.tags.some(t=>`#${t.toLowerCase()}`===word):`${p.name} ${p.id} ${p.description} ${p.author}`.toLowerCase().includes(word))),sort);
  const list=scenario==='empty'?[]:matches;
  const allTags=['UI','Adapter','Tool','Enhancement'];
  const suggested=allTags.filter(tag=>tag.toLowerCase().startsWith(query.slice(query.lastIndexOf('#')+1).toLowerCase()));
  const searchKey=event=>{if(event.nativeEvent.isComposing)return;if(event.key==='Escape'){showTags?setShowTags(false):setQuery('');event.preventDefault();}else if(showTags&&suggested.length){if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();setActiveTag(n=>(n+(event.key==='ArrowDown'?1:-1)+suggested.length)%suggested.length);}else if(event.key==='Enter'){event.preventDefault();chooseTag(suggested[Math.min(activeTag,suggested.length-1)]);}}};
  return <><style>{layout+styling}</style>{toolbar&&ui.createPortal(navigation,toolbar)}<section ref={panel} data-codlet-panel="codlet" data-codlet-view={page}><div className="codlet-scroll">
    <header className="codlet-heading codlet-width"><div className="codlet-heading-inner"><div className="codlet-brand">{page==='settings'?<h1 tabIndex={-1}>设置</h1>:<><Brand size={32}/><h1>Codlet</h1><span className="codlet-version">0.2.0</span><C.Tooltip content="关于 Codlet 技能"><C.Button color="secondary" variant="ghost" size="sm" uniform aria-label="关于 Codlet 技能" onClick={()=>inform('使用 Codlet 技能，在对话中管理插件或询问 Codlet 的用法')}><I.QuestionMarkCircle/></C.Button></C.Tooltip></>}</div><p className="codlet-subtitle">{page==='settings'?'管理 Codlet 偏好与版本更新':'创建或管理 Codlet 插件'}</p></div>{page==='settings'&&<ProjectLinks/>}</header>
    <div className="codlet-body codlet-width">
    {page==='market'&&<><div className="market-breadcrumb"><Back onClick={()=>setPage('plugins')}/><h2>插件市场</h2></div><div className="market-search-anchor"><C.Input ref={search} className="codlet-search market-search" size="md" variant="outline" pill value={query} aria-label="搜索市场插件" placeholder="搜索插件或 #标签" startAdornment={<I.Search width={16} height={16}/>} endAdornment={query?<C.Button color="secondary" variant="ghost" size="sm" uniform aria-label="清空搜索" onClick={()=>{setQuery('');setShowTags(false);}}><I.X/></C.Button>:null} role="combobox" aria-expanded={showTags} aria-controls={showTags?'market-tag-options':undefined} aria-autocomplete="list" onChange={e=>{setQuery(e.target.value);setShowTags(/(?:^|\s)#[a-z]*$/i.test(e.target.value));setActiveTag(0);}} onBlur={()=>setShowTags(false)} onKeyDown={searchKey}/>{showTags&&<div id="market-tag-options" className="codlet-tag-menu" role="listbox" aria-label="标签建议">{suggested.map((tag,index)=><div className="codlet-tag-option" key={tag} role="option" aria-selected={index===activeTag} onPointerMove={()=>setActiveTag(index)} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseTag(tag)}><TagHash/>{tag}</div>)}{!suggested.length&&<div className="codlet-tag-empty" role="status">没有匹配的标签</div>}</div>}</div>
      <div className="market-filterbar"><div className="codlet-filters" role="group" aria-label="插件来源">{[['all','全部'],['official','官方'],['community','社区']].map(([value,label])=><C.Button color="secondary" variant={origin===value?'soft':'ghost'} size="sm" aria-pressed={origin===value} onClick={()=>setOrigin(value)} key={value}>{label}</C.Button>)}</div><div className="market-filter-actions"><C.Checkbox label="仅看适用于此设备" checked={onlyDevice} onCheckedChange={setOnlyDevice}/><C.Menu><C.Menu.Trigger><C.Button color="secondary" variant="ghost" size="sm" aria-label={`排序：${sorts[sort]}`}>{sorts[sort]}<I.ChevronDown/></C.Button></C.Menu.Trigger><C.Menu.Content align="end" minWidth={144}>{Object.entries(sorts).map(([value,label])=><C.Menu.Item key={value} onSelect={()=>setSort(value)} aria-current={sort===value?'true':undefined}>{label}</C.Menu.Item>)}</C.Menu.Content></C.Menu></div></div>
      {scenario==='loading'?<div className="codlet-empty codlet-loading" role="status" aria-label="加载插件市场"><C.LoadingIndicator size={24}/></div>:scenario==='error'?<div className="codlet-empty market-empty"><C.EmptyMessage><C.EmptyMessage.Title>暂时无法加载插件市场</C.EmptyMessage.Title><C.EmptyMessage.Description>请检查网络连接后重试</C.EmptyMessage.Description></C.EmptyMessage><C.Button color="secondary" variant="soft" size="sm" onClick={()=>setScenario('normal')}><I.Regenerate/>重试</C.Button></div>:!list.length?<div className="codlet-empty market-empty"><C.EmptyMessage><C.EmptyMessage.Description>没有匹配的插件</C.EmptyMessage.Description></C.EmptyMessage><C.Button color="secondary" variant="ghost" size="sm" onClick={()=>{setQuery('');setOrigin('all');setOnlyDevice(false);setScenario('normal');}}>清除筛选</C.Button></div>:<div className="codlet-plugin-list">{list.map(plugin=><article className="codlet-plugin-row market-row" key={plugin.id}><div className="codlet-plugin-copy"><div className="codlet-plugin-title"><span className="codlet-plugin-name">{plugin.name}</span><span className="codlet-version">{plugin.version}</span><Tags plugin={plugin} onSelect={chooseTag}/></div><div className="codlet-plugin-description">{plugin.description}</div><div className="market-meta"><Origin plugin={plugin}/><Metrics plugin={plugin}/><Platforms plugin={plugin}/>{compatibility(plugin,device)==='unsupported'&&<span className="market-incompatible">不适用于此设备</span>}</div></div><div className="codlet-plugin-actions"><C.Button color="secondary" variant="ghost" size="sm" aria-label={`查看 ${plugin.name}`} onClick={()=>details(plugin)}>详情</C.Button><Action plugin={plugin}/></div></article>)}</div>}
    </>}
    {page==='plugins'&&<><C.Input className="codlet-search" pill size="md" placeholder="搜索插件" aria-label="搜索已安装插件" startAdornment={<I.Search width={16} height={16}/>} onChange={e=>setQuery(e.target.value)} value={query}/><div className="codlet-list-toolbar" style={{marginTop:24}}><div className="codlet-filters"><C.Button color="secondary" variant="soft" size="sm">全部</C.Button><C.Button color="secondary" variant="ghost" size="sm">已启用</C.Button><C.Button color="secondary" variant="ghost" size="sm">未启用</C.Button></div><C.Button color="secondary" variant="ghost" size="sm" onClick={()=>inform('已安装插件继续使用现有检查更新流程')}><I.Regenerate/>检查更新</C.Button></div><div className="codlet-plugin-list">{plugins.filter(p=>installed[p.id]&&p.name.includes(query)).map(plugin=><div className="codlet-plugin-row" key={plugin.id}><div><div className="codlet-plugin-title"><span className="codlet-plugin-name">{plugin.name}</span><span className="codlet-version">{installed[plugin.id]}</span><Tags plugin={plugin} onSelect={chooseTag}/></div><div className="codlet-plugin-description">{plugin.description}</div></div><div className="codlet-plugin-actions"><C.Button color="secondary" variant="ghost" size="sm" aria-label={`管理 ${plugin.name}`} onClick={()=>details(plugin,'plugins')}>详情</C.Button><C.Button color="secondary" variant="ghost" size="sm" uniform aria-label={`重载 ${plugin.name}`} onClick={()=>inform('预览：重载插件')}><I.Regenerate/></C.Button><C.Switch defaultChecked aria-label={`启用 ${plugin.name}`}/></div></div>)}</div></>}
    {page==='details'&&<section className="codlet-page market-detail"><Back label={from==='market'?'返回插件市场':'返回插件管理'} onClick={()=>setPage(from)}/><div className="market-detail-top"><div className="market-detail-title"><div className="codlet-details-heading"><h2>{selected.name}</h2><span className="codlet-version">{selected.version}</span></div><Copy>{selected.description}</Copy><div className="market-meta" style={{marginTop:0}}><Origin plugin={selected}/><Metrics plugin={selected}/><Tags plugin={selected} onSelect={chooseTag}/></div></div><Action plugin={selected}/></div><Copy>{selected.summary}</Copy>
      <section className="market-detail-section market-compatibility"><div className="market-compat-heading"><h2>系统与兼容性</h2><Status plugin={selected} device={device}/></div><dl><dt>支持系统</dt><dd><SupportedSystems plugin={selected}/>{support(selected).inherited&&<span className="market-inherited">随所需适配器能力确定</span>}</dd><dt>当前设备</dt><dd>{systemNames[device]}</dd><dt>Codex 客户端</dt><dd>{selected.client||'作者尚未声明适配版本'}</dd><dt>Codlet 运行时</dt><dd>API 1</dd></dl></section>
      {selected.dependency&&<section className="market-detail-section"><h2>依赖插件</h2><div className="codlet-permission-line"><Copy>{selected.dependency}</Copy><span className="market-status">已安装</span></div></section>}
      <section className="market-detail-section"><h2>{from==='plugins'?'已授权限':'所需权限'}</h2><ul className="market-permissions">{selected.permissions.map((p,index)=><li key={p}><span>{selected.permissionCopy[index]}</span><br/>{p}</li>)}</ul></section>
      <C.TextLink href={isOfficialPlugin(selected)?`https://github.com/${selected.source.repository}`:undefined} className="market-repo-link" target="_blank" rel="noopener noreferrer" onClick={selected.repository.startsWith('example/')?e=>{e.preventDefault();inform('这是用于展示界面的示例插件，没有真实仓库')}:undefined}>GitHub 项目仓库<I.ArrowUpRight/></C.TextLink>
    </section>}
    {page==='review'&&<section className="codlet-page market-detail"><Back label="返回详情" onClick={()=>setPage('details')}/><div className="market-review-summary"><h2>{updatable(selected)?'更新插件':'安装插件'} · {selected.name}</h2><span className="codlet-version">{updatable(selected)?`${installedVersion(selected)} → `:''}{selected.version}</span></div><div className="market-meta"><Origin plugin={selected}/><Status plugin={selected} device={device}/></div><Copy>支持系统：<SupportedSystems plugin={selected}/></Copy>{compatibility(selected,device)==='unknown'&&<div className="market-review-warning">作者未声明支持的系统，无法确认此插件是否适用于当前设备</div>}{selected.dependency&&<Copy>{`依赖插件：${selected.dependency} · 已安装`}</Copy>}<Copy>{'来源：github.com/'+selected.repository}</Copy><h2>请求的权限</h2>{selected.permissions.map((p,index)=><C.Checkbox key={p} checked={grants.includes(p)} label={`${selected.permissionCopy[index]}（${p}）`} onCheckedChange={checked=>setGrants(old=>checked?[...old,p]:old.filter(v=>v!==p))}/>)}{selected.permissions.includes('host.network')&&<div className="codlet-field"><label htmlFor="preview-origins">允许连接的 API 来源</label><C.Textarea id="preview-origins" rows={2} placeholder="每行一个 HTTP(S) 来源，例如 https://api.example.com"/><Copy>留空时不会授予网络访问</Copy></div>}<C.Checkbox checked={trusted} label="我信任此插件的作者和来源" onCheckedChange={setTrusted}/><C.Checkbox checked={enable} label="安装后立即启用" onCheckedChange={setEnable}/><div className="codlet-actions"><C.Button color="primary" variant="solid" size="md" disabled={!ready||busy} loading={busy} onClick={()=>setNotice(true)}>{updatable(selected)?'确认更新':'确认安装'}</C.Button><C.Button color="secondary" variant="ghost" size="md" onClick={()=>setPage('details')}>取消</C.Button></div></section>}
    {page==='import'&&<section className="codlet-page"><Back onClick={()=>setPage('plugins')}/><C.SegmentedControl defaultValue="github" aria-label="导入来源" size="sm" pill><C.SegmentedControl.Option value="local">本地文件夹</C.SegmentedControl.Option><C.SegmentedControl.Option value="github">GitHub</C.SegmentedControl.Option></C.SegmentedControl><div className="codlet-field"><label>GitHub 仓库或发布链接</label><C.Input placeholder="https://github.com/作者/插件仓库" aria-label="GitHub 仓库或发布链接"/></div><C.Button color="secondary" variant="soft" onClick={()=>inform('手动导入继续沿用现有流程')}><I.Regenerate/>查找版本</C.Button><C.Button color="secondary" variant="ghost" onClick={goMarket}><I.Search/>浏览插件市场</C.Button></section>}
    {page==='settings'&&<SettingsPreview/>}
    </div></div></section>
    <C.Dialog.Root open={notice} onOpenChange={setNotice}><C.Dialog.Portal><C.Dialog.Overlay className="codlet-help-overlay"/><C.Dialog.Content className="codlet-help-dialog codlet-install-notice"><div className="codlet-help-heading"><div className="codlet-install-title"><I.TriangleExclamationErrorWarning className="codlet-install-icon"/><C.Dialog.Title>安装须知</C.Dialog.Title></div><C.Dialog.Close asChild><C.Button color="secondary" variant="ghost" size="sm" uniform aria-label="关闭安装须知"><I.X/></C.Button></C.Dialog.Close></div><C.Dialog.Description className="codlet-install-copy">Codlet不为任何非官方插件的安全性作保障。第三方插件可能访问你的数据或修改客户端，请仅安装你信任的插件</C.Dialog.Description><button className="codlet-inline-link" onClick={()=>inform(`将新建对话：检查 ${selected.repository} 是否存在潜在危险或恶意行为`)}>让 Codex 检查<I.ArrowUpRight/></button><div className="codlet-help-actions codlet-install-actions"><C.Dialog.Close asChild><C.Button color="secondary" variant="outline" size="md">取消</C.Button></C.Dialog.Close><C.Button color="primary" variant="solid" size="md" onClick={install}>知道了</C.Button></div></C.Dialog.Content></C.Dialog.Portal></C.Dialog.Root>
  </>;
}
export function deactivate(){ui?.dispose();settingsManager?.dispose();ui=settingsManager=null;}
export async function activate(context){
  deactivate();context.onDeactivate(deactivate);ui=context.ui.create();({React,components:C,icons:I}=ui);h=React.createElement;I=createCodletIcons(React,I);Brand=createCodletIcon(React);
  const demo=createPreviewRuntime();
  settingsManager=new Manager({pluginId:'codlet-gui',i18n:{locale:'zh'},rpc:{request:demo.request}});
  const t=settingsManager.messages.t;
  Settings=createSettingsView({React,C,I,manager:settingsManager,t,Copy,mutationBusy:()=>false});
  ProjectLinks=createProjectLinks({React,C,I,t});
  await ui.page({label:'Codlet',icon:'Codlet',toolbar:true,render:({toolbar})=><App toolbar={toolbar}/>});
}
