import assert from 'node:assert/strict';
import test from 'node:test';
import { EventEmitter } from 'node:events';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
const { installElectronTraffic } = createRequire(import.meta.url)('../host/electron-traffic.cjs');
const fixtures = new URL('./fixtures/traffic/', import.meta.url);
test('Electron main hook limits trust to the launch CA/hostname and proxy authentication to its endpoint', async () => {
  const [caPem, cert] = await Promise.all(['ca.pem', 'cert.pem'].map(name => fs.readFile(new URL(name, fixtures), 'utf8')));
  const app = new EventEmitter(); let ready = false;
  app.isReady = () => ready; app.whenReady = () => Promise.resolve();
  const proxies = []; let verify;
  const session = { defaultSession: { setCertificateVerifyProc(value) { verify = value; }, async setProxy(value) { proxies.push(value); }, async closeAllConnections() {} } };
  const hook = installElectronTraffic({ app, session }, { proxyUrl: 'http://codlet:fixture@127.0.0.1:12345', caPem });
  ready = true; app.emit('ready'); await hook.ready();
  assert.equal(proxies[0].proxyRules, 'http=127.0.0.1:12345;https=127.0.0.1:12345');
  const checked = hostname => new Promise(resolve => verify({ hostname, certificate: { data: cert } }, resolve));
  assert.equal(await checked('codlet-probe.invalid'), 0);
  assert.equal(await checked('attacker.invalid'), -3);
  assert.equal(await new Promise(resolve => verify({ hostname: 'codlet-probe.invalid', certificate: { data: caPem } }, resolve)), -3);
  let prevented = 0, credentials = null;
  const event = { preventDefault() { prevented++; } }, receive = (...values) => { credentials = values; };
  app.emit('login', event, null, {}, { isProxy: false, host: '127.0.0.1', port: 12345 }, receive);
  assert.equal(credentials, null);
  app.emit('login', event, null, {}, { isProxy: true, host: 'other.invalid', port: 12345 }, receive);
  assert.equal(credentials, null);
  app.emit('login', event, null, {}, { isProxy: true, host: '127.0.0.1', port: 12345 }, receive);
  assert.deepEqual(credentials, ['codlet', 'fixture']); assert.equal(prevented, 1);
  assert.equal(hook.inspect().available, false);
  await hook.close(); assert.equal(verify, null); assert.deepEqual(proxies.at(-1), { mode: 'system' });
  assert.equal(app.listenerCount('session-created'), 0); assert.equal(app.listenerCount('login'), 0);
  assert.throws(() => installElectronTraffic({ app, session }, { proxyUrl: 'invalid', caPem }), { code: 'electron_bootstrap_too_late' });
});
